name: Python-Unit-Testing

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    paths:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.6]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black (Python code formatter)
        run: |
          black --check .

      # - name: Run Tests
      #   run: |
      #     python manage.py test
